set nocompatible
set encoding=utf-8
filetype plugin indent on
syntax on

"if has("autocmd")
"  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
"endif

if has("autocmd")
  filetype plugin indent on
endif

set showcmd		" Show (partial) command in status line.
set showmatch		" Show matching brackets.
set ignorecase		" Do case insensitive matching
set smartcase		" Do smart case matching
set incsearch		" Incremental search
"set autowrite		" Automatically save before commands like :next and :make
"set hidden		" Hide buffers when they are abandoned
"set mouse=a		" Enable mouse usage (all modes)

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

:set tabstop=2
:set shiftwidth=2
:set expandtab

set path=$PWD/**

set shell=bash

:noremap <C-P> @:<CR>

" map <C-j> <C-W>j
" map <C-k> <C-W>k
" map <C-h> <C-W>h
" map <C-l> <C-W>l

set autoindent
set number
highlight LineNr ctermfg=5

map <C-J> <C-W>j<C-W>_
map <C-K> <C-W>k<C-W>_
map <C-H> <C-W>h<C-W>_
map <C-L> <C-W>l<C-W>_

set pastetoggle=<F2>

noremap <F9> gT
noremap <F10> gt

:set incsearch
:set hlsearch
nmap <silent> <BS> :nohlsearch<CR>

nmap <space> zz
nmap n nzz
nmap N Nzz

call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rails'
Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'tomtom/tlib_vim'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'ervandew/supertab'
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'KurtPreston/vim-autoformat-rails'
"Plug 'bling/vim-airline'
"Plug 'vim-airline/vim-airline-themes'
Plug 'sukima/xmledit'
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'airblade/vim-gitgutter'
Plug 'myusuf3/numbers.vim'
Plug 'Raimondi/delimitMate'
Plug 'docunext/closetag.vim'
Plug 'gregsexton/MatchTag'
Plug 'pangloss/vim-javascript'
Plug 'nathanaelkane/vim-indent-guides'
"Plug 'othree/javascript-libraries-syntax.vim'
"Plug 'scrooloose/syntastic'
"Plug 'matthewsimo/angular-vim-snippets'
"Plug 'tpope/vim-haml'
Plug 'tpope/vim-surround'
"Plug 'nelstrom/vim-markdown-folding'
"Plug 'bruno-/vim-ruby-fold'
"Plug 'godlygeek/tabular'
"Plug 'plasticboy/vim-markdown'
Plug 'rking/ag.vim'
Plug 'tmhedberg/matchit'
"Plug 'fatih/vim-go'
Plug 'elixir-lang/vim-elixir'
Plug 'mxw/vim-jsx'
Plug 'christoomey/vim-tmux-navigator'
" Plug 'ryanoasis/vim-devicons'
Plug 'ntpeters/vim-better-whitespace'
Plug 'isRuslan/vim-es6'
Plug 'vim-utils/vim-man'
Plug 'leafgarland/typescript-vim'
Plug 'posva/vim-vue'
Plug 'mattn/emmet-vim'
Plug 'DrawIt'
Plug 'slim-template/vim-slim'
Plug 'kchmck/vim-coffee-script'
Plug 'gaogao1030/vim-skim'
Plug 'junegunn/vim-easy-align'
Plug 'jreybert/vimagit'
Plug 'tpope/vim-repeat'
Plug 'sjl/gundo.vim'
Plug 'othree/html5.vim'
Plug 'elzr/vim-json'
Plug 'jelera/vim-javascript-syntax'
Plug 'rust-lang/rust.vim'
Plug 'rhysd/vim-crystal'
Plug 'vim-ruby/vim-ruby'
Plug 'godlygeek/tabular'
Plug 'jgdavey/vim-blockle'

" Themes below
Plug 'sjl/badwolf'
Plug 'wellsjo/wells-colorscheme.vim'
Plug 'ajgrf/sprinkles'
Plug 'stulzer/heroku-colorscheme'
Plug 'CruizeMissile/Revolution.vim'
Plug 'whatyouhide/vim-gotham'
Plug 'farseer90718/flattr.vim'
Plug 'tomasr/molokai'
Plug 'vim-scripts/BusyBee'
Plug 'gregsexton/Muon'
Plug 'desert-warm-256'
Plug 'flazz/vim-colorschemes'
Plug 'altercation/vim-colors-solarized'
Plug 'aliou/moriarty.vim'
Plug 'morhetz/gruvbox'
" Themes above

call plug#end()
" Syntastic
" set statusline+=%#warningmsg#
" set statusline+=%{SyntasticStatuslineFlag()}
" set statusline+=%*
"
" let g:syntastic_ruby_checkers          = ['rubocop']
" let g:syntastic_ruby_rubocop_exec      = '/home/b/.rvm/rubies/ruby-2.3.0/bin/ruby  /home/b/.rvm/gems/ruby-2.3.0/bin/rubocop'
" let g:syntastic_loc_list_height =3
" let g:syntastic_always_populate_loc_list = 1
" let g:syntastic_auto_loc_list = 1
" let g:syntastic_check_on_open = 1
" let g:syntastic_check_on_wq = 0

"let g:syntastic_mode_map = { 'mode': 'passive', 'active_filetypes': [],'passive_filetypes': [] }
"nnoremap <C-w>E :SyntasticCheck<CR> :SyntasticToggleMode<CR>

" better key bindings for UltiSnipsExpandTrigger
let g:UltiSnipsExpandTrigger = "<tab>"
let g:UltiSnipsJumpForwardTrigger = "<tab>"
let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"

" All of your Plugins must be added before the following line
filetype plugin indent on    " required
set tags=./tags;
set grepprg=ack
set wildmenu
set winminheight=0

set backspace=indent,eol,start

set wildignore+=*/node_modules/*
set runtimepath^=~/.vim/bundle/ctrlp.vim
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_switch_buffer = 0

let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/](\.(git|hg|svn)|\_site|node_modules)$',
  \ 'file': '\v\.(exe|so|dll|class|png|jpg|jpeg)$',
  \}

" Folding with space
" nnoremap <Space> za

" if exists('$TMUX')
"   let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
"   let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
" else
"   let &t_SI = "\<Esc>]50;CursorShape=1\x7"
"   let &t_EI = "\<Esc>]50;CursorShape=0\x7"
" endif

set backup
set backupdir=~/.vim-tmp,~/.tmp,/var/tmp,/tmp
set backupskip=/tmp/*,/private/tmp/*
set directory=~/.vim-tmp,~/.tmp,/var/tmp,/tmp
set writebackup

" let g:airline#extensions#tabline#enabled = 0
" let g:airline#extensions#tabline#fnamemod = ':t'
" let g:airline_powerline_fonts = 0
set laststatus=2

"autocmd vimenter * NERDTree
map <C-n> :NERDTreeToggle<CR>

set cursorline
"hi CursorLine   cterm=NONE ctermbg=8
set fillchars+=vert:\ 

set t_Co=256
set background=dark
colorscheme gruvbox
hi CursorLine term=bold cterm=bold ctermbg=233

highlight Normal ctermbg=NONE
highlight NonText ctermbg=NONE
highlight Comment ctermbg=NONE
highlight Constant ctermbg=NONE
highlight Identifier ctermbg=NONE
highlight Cursor ctermbg=NONE
highlight String ctermbg=NONE
highlight Character ctermbg=NONE
highlight Number ctermbg=NONE
highlight Special ctermbg=NONE
highlight Folded ctermbg=NONE
highlight PreProc ctermbg=NONE

hi! VertSplit ctermfg=NONE ctermbg=NONE term=NONE

let g:javascript_enable_domhtmlcss = 1
imap <C-J> <Plug>snipMateNextOrTrigger
smap <C-J> <Plug>snipMateNextOrTrigger

map <C-c> "+y

nnoremap <silent> <C-S> :<C-u>Update<CR>
inoremap <silent> <C-S> :<Esc><C-u>Update<CR>i

" this is needed by webpack. it ensures that original file is overwritten:
set backupcopy=yes

" more natural behavior
  set splitbelow
  set splitright

hi StatusLine                  ctermfg=7     ctermbg=8     cterm=NONE
hi StatusLineNC                ctermfg=2     ctermbg=8     cterm=NONE

set shell=/bin/bash

command -nargs=0 -bar Update if &modified
                           \|    if empty(bufname('%'))
                           \|        browse confirm write
                           \|    else
                           \|        confirm write
                           \|    endif
                           \|endif

nnoremap <F5> :CtrlPClearCache<cr>call NERDTreeMapRefreshRoot()<cr>
function! NERDTreeMapRefreshRoot()
    if nerdtree#isTreeOpen()
        call nerdtree#putCursorInTreeWin()
        call nerdtree#invokeKeyMap('R')
        " Go back to previous window.
        wincmd p
    endif
endfunction

autocmd FileType ruby compiler ruby
let g:gundo_prefer_python3 = 1
nnoremap <F4> :GundoToggle<CR>
:let mapleader = ","
